### PR TITLE
encoding updated to utf8 in dockerfile

### PR DESCRIPTION
**Pull request by rshorey**

### CODE REVIEW

**Comment by paultag** [comment]
:+1: nice one!

**Comment by rshorey** [comment]
@paultag does anything need to be done for this to be pushed to moxie, or does that just happen automagically?

**Comment by paultag** [comment]
@rshorey that happens on its own, only only configuration changes that need a poke

**Comment by rshorey** [comment]
ok, thanks, I'll kick the jobs in question and see if this fix does it!

**Comment by paultag** [comment]
You can check on the image build status at
https://registry.hub.docker.com/repos/sunlightlabs/ :) :+1:

On Wed, Jun 24, 2015 at 4:57 PM, Rachel <notifications@github.com> wrote:

> ok, thanks, I'll kick the jobs in question and see if this fix does it!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/opencivicdata/pupa/pull/193#issuecomment-115010178>.
>



-- 
Paul Tagliamonte
Software Developer | Sunlight Foundation

**Pull request merged**
