### PR TITLE
Fix database engine on Heroku

### PR DESCRIPTION
**Pull request by jpmckinney**
I don't know why I had to fix a merge, but anyway, the change is one line.

### CODE REVIEW

**Comment by jamesturk** [comment]
have you tried setting the db url to start with postgis:// ? is this still needed

**Comment by jpmckinney** [comment]
Heroku sets its own DATABASE_URL. Touching it is problems.

**Comment by jpmckinney** [comment]
This patch is the same as Heroku's recommended approach: https://devcenter.heroku.com/articles/postgis#geodjango-setup

**Comment by jamesturk** [comment]
Ah ok, will merge!

**Pull request merged**
