### PR TITLE
add date argument to add_abstract method, modify tests and schema

### PR DESCRIPTION
**Pull request by crdunwel**

### CODE REVIEW

**Comment by crdunwel** [comment]
blah

**Comment by paultag** [comment]
Looks like tests aren't passing :)

**Comment by crdunwel** [comment]
fear not, it shall be resolved

**Comment by crdunwel** [comment]
ehhh do migrations run automatically on the test server? BillAbstract should have date field per https://github.com/opencivicdata/python-opencivicdata-django/commit/220d81a81ffa14534c24553c3a3bbba9b1383361

**Comment by paultag** [comment]
I've kicked off the tests again; we'll see if it was a race. Migrations do get run. I wonder if we need to make a release of ocd-django to pypi.

**Comment by crdunwel** [comment]
=(

**Comment by paultag** [comment]
It's NBD; we just need a release of opencivicdata-django

**Comment by paultag** [comment]
OK, I did a release. Re-running tests.

**Comment by crdunwel** [comment]
:cool:

**Comment by paultag** [comment]
Thanks!

**Comment by crdunwel** [comment]
:smiley:

**Pull request merged**
