### PR TITLE
add migrate command

### PR DESCRIPTION
**Pull request by fgregg**
This adds a way to update an existing opencivicdata database through pupa.

### CODE REVIEW

**Comment by jamesturk** [comment]
Wait, can we discuss this?  django-admin has the exact same command

**Comment by jamesturk** [comment]
talked w/ @fgregg on Slack some, I think my only issue is us being careful what we add (I'd hate to see us go down the road of adding django-admin shell, etc. too)

perhaps we need some documentation pointing people towards django-admin for Django-specific tasks, or perhaps pupa migrate is the sole exception and we're OK adding it

**Comment by fgregg** [comment]
I didn't know about `django-admin migrate`.  

I think it's fine if we want to go that route, but heres the reasons why it might make sense to have as a pupa command.

We already have other database management commands as part of pupa, seems weird that you use pupa to set up a database and other tool to update the database

If we don't add it, we'll need good documentation for `django-admin`

**Comment by jpmckinney** [comment]
I opened #259. I prefer documenting `django-admin`

**Pull request merged**
