### PR TITLE
Add classification field to EventAgendaItem

### PR DESCRIPTION
**Pull request by patcon**
This is reticketed from here https://github.com/opencivicdata/scrapers-ca/pull/168#issuecomment-173796717

Presumably I would start with a PR to [`opencivicdata/python-opencivicdata-django`](https://github.com/opencivicdata/python-opencivicdata-django/blob/master/opencivicdata/models/event.py), but it seemed to make most sense to ask for a blessing here first :)

Would adding a classification to agenda items be an acceptable approach?

### CODE REVIEW

**Comment by patcon** [comment]
Coffeeshop is closing, but I'll test this after against.

https://github.com/patcon/python-opencivicdata-django/tree/add-eventagendaitem-classifiation

**Comment by patcon** [comment]
Blocked on merge of https://github.com/opencivicdata/python-opencivicdata-django/pull/57

**Comment by jpmckinney** [comment]
Can you re-push to see if tests pass now that I merged the blocking PR?

**Comment by patcon** [comment]
I think we need to peel another opencivicdata-django release before this will pass. Currently locked at 0.8.0, if I understand pip correctly, and we've released up to 0.8.2

I'll add a dependency link in the meantime, to confirm this would pass

**Comment by jpmckinney** [comment]
We'd need to make a 0.9.0 release of opencivicdata-django, and likewise a new branch of pupa I imagine. I don't know what the big deal is about requiring folks to run a small migration, but that was the reason for putting the new field under 0.9.0.

**Comment by jamesturk** [comment]
Glad to do a release of 0.9.0 whenever it makes sense to.  I think it's a good idea to keep to a pattern where bugfix releases don't require migrations as it'll mess w/ existing deployments.

If there are other backwards-incompatible changes coming (I'm mainly thinking of the Document refactor) does it make sense to include that in 0.9 too so that it doesn't require cutting yet another release?  Glad to do it either way depending on urgency of these changes being in a release.

**Comment by patcon** [comment]
My personal feelings is that features should rarely be held up waiting for a version bump -- version bumps are just a technical event that happens with certain sorts of changes -- no need to make ceremony of it imho.

in this case we can just bump the minor version twice in relatively quick succession, right? we're just a small group of people who are all talking, so it's not like we have too much release complication :)

**Comment by jamesturk** [comment]
if people are waiting on the feature then yep I definitely agree, I wasn't sure of the urgency or how far we were from landing on a decision on the Document stuff. (was just saying doing a release before it's needed doesn't have much upside)

**Comment by jamesturk** [comment]
I'll take everyone's word for it though, just open an issue whenever we need 0.9.0 cut (and please update the changelog) and I'll get it onto PyPI

**Comment by patcon** [comment]
@jamesturk @jpmckinney any objection to my loosening this constraint (to be `>=`) so that we can more easily use a newer django-opencivicdata package with our scrapers?
https://github.com/opencivicdata/pupa/blob/master/setup.py#L21

 as it stands, i need to use a custom pupa with this loosened, which a little bit of a hoop :)

**Comment by patcon** [comment]
If so, please merge this:
https://github.com/opencivicdata/pupa/pull/235

**Comment by patcon** [comment]
^^^ (ability to make this pass, even in a PR depends on that)

**Comment by patcon** [comment]
rebased against that blocking PR for now, and force-pushed this branch

**Comment by patcon** [comment]
great! Unless I'm forgetting context, I think this is good for review/merge :)

Happy to squash on request

**Comment by jpmckinney** [comment]
Hmm, if we merge this without cutting a release of django-opencivicdata, then pupa will not run correctly unless the user happens to know to use the git version of django-opencivicdata. I think we need to cut a release of django-opencivicdata first.

**Comment by patcon** [comment]
That makes sense. Mostly wanted to prove to myself that this was finally passing

Possible to tag a release @jamesturk?

**Pull request merged**
