### PR TITLE
Prepare for 0.10.2 release

### PR DESCRIPTION
**Pull request by hancush**
## Description

This PR bumps the module version and updates the CHANGELOG in preparation for a new release.

### CODE REVIEW

**Comment by fgregg** [comment]
Okay, we are all set up. I added a PYPI_TOKEN secret to this repo and python-opencivicdata.

You can use this pattern to upload to pypi. https://github.com/datamade/census/blob/master/.github/workflows/python-package.yml#L43-L53

**Comment by hancush** [comment]
@fgregg Adding GitHub Actions to my fork didn't trigger builds, so I implemented those in a branch off this repository: #338

**Comment by fgregg** [comment]
@hancush is this a stale PR now?

**Comment by hancush** [comment]
@fgregg No, I need to merge and push a tag to cut a release for the changes described in the change log.

**Pull request merged**
