### PR TITLE
Use class names that are consistent with python-opencivicdata-django

### LINKED ISSUE #148: Pupa uses the term "Vote" but python-opencivicdata-django uses the term "VoteEvent"
VoteEvent should be the universal term.

### PR DESCRIPTION
**Pull request by jpmckinney**
Closes #148 

/cc #147

### CODE REVIEW

**Comment by jpmckinney** [comment]
Note that this is backwards-incompatible, but in my own scraper code, I just had to change `from pupa.scrape import Vote` to use `VoteEvent` and all other occurrences of the `Vote` class name.

**Comment by jamesturk** [comment]
i'll look at this for 0.5

this may be slightly too aggressive in that it changes a migration but I think if I roll that back and make a new migration (and maybe rename the test files back initially so I can diff them more easily) this should be OK to merge

**Comment by jpmckinney** [comment]
Sounds reasonable. I can do the rename in a second commit to make the diff easier.

**Comment by jamesturk** [comment]
used a branch to review w/o the big diffs, everything looks fine to me, merging this

**Pull request merged**
