### PR TITLE
check if Jurisdiction has `get_session_list` defined.

### PR DESCRIPTION
**Pull request by fgregg**

### CODE REVIEW

**Comment by fgregg** [comment]
@jamesturk this is good to go.

**Comment by jpmckinney** [comment]
@fgregg If `juris` has the attribute but it is set to `None` it should still skip. The PR changes that behavior.

**Comment by fgregg** [comment]
That's true, but this behavior didn't exist before six days ago. https://github.com/opencivicdata/pupa/commit/c54e8969f6dae1d3de364c31e5ee2a0cf0b69925#commitcomment-20440348

Let me know if you want me to handle both cases.

**Comment by jamesturk** [comment]
I'm OK w/ it just checking if it is present, I don't think there's anyone
out there that this would affect.

**Comment by jpmckinney** [comment]
Ah, nevermind - thought it was older.

**Pull request merged**
