### PR TITLE
add convenience method for vote entity relation in EventAgendaItem

### PR DESCRIPTION
**Pull request by crdunwel**

### CODE REVIEW

**Comment by paultag** [comment]
Can we add a test to confirm this resolves right?

**Comment by crdunwel** [comment]
sure ^

**Comment by paultag** [comment]
@crdunwel can you run it through the import pipeline, fetch it from the db and assert there?

**Comment by crdunwel** [comment]
may be, can you link to examples of methods that test this way currently?

**Comment by crdunwel** [comment]
^^^

**Comment by paultag** [comment]
Sure!

**Comment by paultag** [comment]
Thanks!

**Pull request merged**
