### PR TITLE
this branch disables imports of extras and switches things to Django 1.8

### PR DESCRIPTION
**Pull request by jamesturk**
it can be merged before the database is rebuilt, it just stops assuming extras is there

### CODE REVIEW

**Comment by paultag** [comment]
looks like it's bombing out because `ImportError: No module named 'djorm_pgarray'` is missing (used in `opencivicdata/models/jurisdiction.py`); so I'll hold off until we sync with pyocd? Any reason to drop it in before?

**Comment by jamesturk** [comment]
yeah, it shouldn't break anything but we need a py-ocd-django release before the travis tests will pass

this may not even be necessary pending a decision on short term options for extras

**Comment by jamesturk** [comment]
going to close this PR, I think we're avoiding this now

**Comment by paultag** [comment]
Yeah, I was just looking into this, since somewhere we still talk extras in Jurisdictions:

```
    return self.import_data(json_stream())
  File "/home/tag/.virtualenvs/ocd/src/pupa/pupa/importers/base.py", line 202, in import_data
    obj_id, what = self.import_item(data)
  File "/home/tag/.virtualenvs/ocd/src/pupa/pupa/importers/base.py", line 240, in import_item
    if getattr(obj, key) != value:
AttributeError: 'Jurisdiction' object has no attribute 'extras'
```

but yeah, I think we can deal with that ad-hoc

**Pull request closed without merging**
