### PR TITLE
Reduce default scrape RPM from 60 to 55

### PR DESCRIPTION
**Pull request by estaub**
Rate-limiters are likely to be set to 60, which would lead to intermittent failures when the request rate is exactly the same as the limit.  This may be occurring in Kansas https://github.com/openstates/openstates/issues/1739 ; regardless, this seems like a good idea.

### CODE REVIEW

**Comment by fgregg** [comment]
Since, this is something that can be set on the command line. 

`pupa update -r 55 foo`

I would urge against bringing in this PR.

**Comment by estaub** [comment]
To be clear, I'm not suggesting this to fix the Kansas problem; I've put in a PR specific to that.  It just seems like a default of 60 is asking for trouble.  if I were rate-limiting, I'd set it to ~65, not 60, just to avoid mystery fails.

**Comment by showerst** [comment]
What do you mean by "Rate-limiters are likely to be set to 60"? Like on the third-party website side?

FWIW on the openstates side I don't think there are any states that need it set at 55-65. In govhawk's setup we run limiters on KS, OR, and VA. OR and VA at 30, KS a little lower.

**Comment by estaub** [comment]
@showerst Yes, I meant the third-party sites.  OK, thanks for the numbers!  Closing.

**Pull request closed without merging**
